### ISSUE TITLE
Text disappear on lost focus

### ISSUE THREAD

**Issue by krzyzanowskim** [davbeck/TURecipientBar#25]
it's somewehere in textFieldShouldEndEditing but if label contains only text and lost focus, then text disappear and placeholder is visible.

record: http://f.cl.ly/items/2A0B2x3o0a3r0Z253r3q/TURecipientBar.mov

**Comment by davbeck** [comment]
This is intended behavior. There are several ways to customize it, for instance you can create a token based on what has been entered when the user ends editing or disable ending editing completely. The text field is not meant to be part of the input, but more of a search field for tokens.
