### ISSUE TITLE
CocoaPod seems out of date

### ISSUE THREAD

**Issue by mattnico** [davbeck/TURecipientBar#28]
When installing via CocoaPods I seem to be pulling an old version of `TURecipientsBar.h` and TURecipientsBar.m` which doesn't even include `setSearchFieldTextAttributes`.

I notice that the `TURecipientBar.podspec` file was last committed 9 months ago while the `TURecipientsBar` files were committed 3 months ago. Perhaps the `.podspec` file needs updated? (I'm not personally familiar with publishing on CocoaPods, just installing from it.)

**Comment by davbeck** [comment]
It should be more up to date now.
